// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModuleRegister.proto

#ifndef PROTOBUF_INCLUDED_ModuleRegister_2eproto
#define PROTOBUF_INCLUDED_ModuleRegister_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ModuleRegister_2eproto 

namespace protobuf_ModuleRegister_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ModuleRegister_2eproto
namespace CMSGProto {
class module_register_reply;
class module_register_replyDefaultTypeInternal;
extern module_register_replyDefaultTypeInternal _module_register_reply_default_instance_;
class module_register_req;
class module_register_reqDefaultTypeInternal;
extern module_register_reqDefaultTypeInternal _module_register_req_default_instance_;
class multi_module_register_reply;
class multi_module_register_replyDefaultTypeInternal;
extern multi_module_register_replyDefaultTypeInternal _multi_module_register_reply_default_instance_;
class multi_module_register_req;
class multi_module_register_reqDefaultTypeInternal;
extern multi_module_register_reqDefaultTypeInternal _multi_module_register_req_default_instance_;
}  // namespace CMSGProto
namespace google {
namespace protobuf {
template<> ::CMSGProto::module_register_reply* Arena::CreateMaybeMessage<::CMSGProto::module_register_reply>(Arena*);
template<> ::CMSGProto::module_register_req* Arena::CreateMaybeMessage<::CMSGProto::module_register_req>(Arena*);
template<> ::CMSGProto::multi_module_register_reply* Arena::CreateMaybeMessage<::CMSGProto::multi_module_register_reply>(Arena*);
template<> ::CMSGProto::multi_module_register_req* Arena::CreateMaybeMessage<::CMSGProto::multi_module_register_req>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace CMSGProto {

// ===================================================================

class module_register_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSGProto.module_register_req) */ {
 public:
  module_register_req();
  virtual ~module_register_req();

  module_register_req(const module_register_req& from);

  inline module_register_req& operator=(const module_register_req& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  module_register_req(module_register_req&& from) noexcept
    : module_register_req() {
    *this = ::std::move(from);
  }

  inline module_register_req& operator=(module_register_req&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const module_register_req& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const module_register_req* internal_default_instance() {
    return reinterpret_cast<const module_register_req*>(
               &_module_register_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(module_register_req* other);
  friend void swap(module_register_req& a, module_register_req& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline module_register_req* New() const final {
    return CreateMaybeMessage<module_register_req>(NULL);
  }

  module_register_req* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<module_register_req>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const module_register_req& from);
  void MergeFrom(const module_register_req& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(module_register_req* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CMSGProto.module_register_req)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_ModuleRegister_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class module_register_reply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSGProto.module_register_reply) */ {
 public:
  module_register_reply();
  virtual ~module_register_reply();

  module_register_reply(const module_register_reply& from);

  inline module_register_reply& operator=(const module_register_reply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  module_register_reply(module_register_reply&& from) noexcept
    : module_register_reply() {
    *this = ::std::move(from);
  }

  inline module_register_reply& operator=(module_register_reply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const module_register_reply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const module_register_reply* internal_default_instance() {
    return reinterpret_cast<const module_register_reply*>(
               &_module_register_reply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(module_register_reply* other);
  friend void swap(module_register_reply& a, module_register_reply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline module_register_reply* New() const final {
    return CreateMaybeMessage<module_register_reply>(NULL);
  }

  module_register_reply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<module_register_reply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const module_register_reply& from);
  void MergeFrom(const module_register_reply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(module_register_reply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:CMSGProto.module_register_reply)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_name();
  void clear_has_name();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_ModuleRegister_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class multi_module_register_req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSGProto.multi_module_register_req) */ {
 public:
  multi_module_register_req();
  virtual ~multi_module_register_req();

  multi_module_register_req(const multi_module_register_req& from);

  inline multi_module_register_req& operator=(const multi_module_register_req& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  multi_module_register_req(multi_module_register_req&& from) noexcept
    : multi_module_register_req() {
    *this = ::std::move(from);
  }

  inline multi_module_register_req& operator=(multi_module_register_req&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const multi_module_register_req& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const multi_module_register_req* internal_default_instance() {
    return reinterpret_cast<const multi_module_register_req*>(
               &_multi_module_register_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(multi_module_register_req* other);
  friend void swap(multi_module_register_req& a, multi_module_register_req& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline multi_module_register_req* New() const final {
    return CreateMaybeMessage<multi_module_register_req>(NULL);
  }

  multi_module_register_req* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<multi_module_register_req>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const multi_module_register_req& from);
  void MergeFrom(const multi_module_register_req& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(multi_module_register_req* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CMSGProto.module_register_req module_info = 1;
  int module_info_size() const;
  void clear_module_info();
  static const int kModuleInfoFieldNumber = 1;
  ::CMSGProto::module_register_req* mutable_module_info(int index);
  ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_req >*
      mutable_module_info();
  const ::CMSGProto::module_register_req& module_info(int index) const;
  ::CMSGProto::module_register_req* add_module_info();
  const ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_req >&
      module_info() const;

  // @@protoc_insertion_point(class_scope:CMSGProto.multi_module_register_req)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_req > module_info_;
  friend struct ::protobuf_ModuleRegister_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class multi_module_register_reply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CMSGProto.multi_module_register_reply) */ {
 public:
  multi_module_register_reply();
  virtual ~multi_module_register_reply();

  multi_module_register_reply(const multi_module_register_reply& from);

  inline multi_module_register_reply& operator=(const multi_module_register_reply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  multi_module_register_reply(multi_module_register_reply&& from) noexcept
    : multi_module_register_reply() {
    *this = ::std::move(from);
  }

  inline multi_module_register_reply& operator=(multi_module_register_reply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const multi_module_register_reply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const multi_module_register_reply* internal_default_instance() {
    return reinterpret_cast<const multi_module_register_reply*>(
               &_multi_module_register_reply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(multi_module_register_reply* other);
  friend void swap(multi_module_register_reply& a, multi_module_register_reply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline multi_module_register_reply* New() const final {
    return CreateMaybeMessage<multi_module_register_reply>(NULL);
  }

  multi_module_register_reply* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<multi_module_register_reply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const multi_module_register_reply& from);
  void MergeFrom(const multi_module_register_reply& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(multi_module_register_reply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .CMSGProto.module_register_reply module_info = 1;
  int module_info_size() const;
  void clear_module_info();
  static const int kModuleInfoFieldNumber = 1;
  ::CMSGProto::module_register_reply* mutable_module_info(int index);
  ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_reply >*
      mutable_module_info();
  const ::CMSGProto::module_register_reply& module_info(int index) const;
  ::CMSGProto::module_register_reply* add_module_info();
  const ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_reply >&
      module_info() const;

  // @@protoc_insertion_point(class_scope:CMSGProto.multi_module_register_reply)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_reply > module_info_;
  friend struct ::protobuf_ModuleRegister_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// module_register_req

// required int32 id = 1;
inline bool module_register_req::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void module_register_req::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void module_register_req::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void module_register_req::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 module_register_req::id() const {
  // @@protoc_insertion_point(field_get:CMSGProto.module_register_req.id)
  return id_;
}
inline void module_register_req::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:CMSGProto.module_register_req.id)
}

// required string name = 2;
inline bool module_register_req::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void module_register_req::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void module_register_req::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void module_register_req::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& module_register_req::name() const {
  // @@protoc_insertion_point(field_get:CMSGProto.module_register_req.name)
  return name_.GetNoArena();
}
inline void module_register_req::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSGProto.module_register_req.name)
}
#if LANG_CXX11
inline void module_register_req::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMSGProto.module_register_req.name)
}
#endif
inline void module_register_req::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSGProto.module_register_req.name)
}
inline void module_register_req::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSGProto.module_register_req.name)
}
inline ::std::string* module_register_req::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:CMSGProto.module_register_req.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* module_register_req::release_name() {
  // @@protoc_insertion_point(field_release:CMSGProto.module_register_req.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void module_register_req::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CMSGProto.module_register_req.name)
}

// -------------------------------------------------------------------

// module_register_reply

// required int32 id = 1;
inline bool module_register_reply::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void module_register_reply::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void module_register_reply::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void module_register_reply::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 module_register_reply::id() const {
  // @@protoc_insertion_point(field_get:CMSGProto.module_register_reply.id)
  return id_;
}
inline void module_register_reply::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:CMSGProto.module_register_reply.id)
}

// required string name = 2;
inline bool module_register_reply::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void module_register_reply::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void module_register_reply::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void module_register_reply::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& module_register_reply::name() const {
  // @@protoc_insertion_point(field_get:CMSGProto.module_register_reply.name)
  return name_.GetNoArena();
}
inline void module_register_reply::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:CMSGProto.module_register_reply.name)
}
#if LANG_CXX11
inline void module_register_reply::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:CMSGProto.module_register_reply.name)
}
#endif
inline void module_register_reply::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:CMSGProto.module_register_reply.name)
}
inline void module_register_reply::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:CMSGProto.module_register_reply.name)
}
inline ::std::string* module_register_reply::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:CMSGProto.module_register_reply.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* module_register_reply::release_name() {
  // @@protoc_insertion_point(field_release:CMSGProto.module_register_reply.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void module_register_reply::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:CMSGProto.module_register_reply.name)
}

// -------------------------------------------------------------------

// multi_module_register_req

// repeated .CMSGProto.module_register_req module_info = 1;
inline int multi_module_register_req::module_info_size() const {
  return module_info_.size();
}
inline void multi_module_register_req::clear_module_info() {
  module_info_.Clear();
}
inline ::CMSGProto::module_register_req* multi_module_register_req::mutable_module_info(int index) {
  // @@protoc_insertion_point(field_mutable:CMSGProto.multi_module_register_req.module_info)
  return module_info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_req >*
multi_module_register_req::mutable_module_info() {
  // @@protoc_insertion_point(field_mutable_list:CMSGProto.multi_module_register_req.module_info)
  return &module_info_;
}
inline const ::CMSGProto::module_register_req& multi_module_register_req::module_info(int index) const {
  // @@protoc_insertion_point(field_get:CMSGProto.multi_module_register_req.module_info)
  return module_info_.Get(index);
}
inline ::CMSGProto::module_register_req* multi_module_register_req::add_module_info() {
  // @@protoc_insertion_point(field_add:CMSGProto.multi_module_register_req.module_info)
  return module_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_req >&
multi_module_register_req::module_info() const {
  // @@protoc_insertion_point(field_list:CMSGProto.multi_module_register_req.module_info)
  return module_info_;
}

// -------------------------------------------------------------------

// multi_module_register_reply

// repeated .CMSGProto.module_register_reply module_info = 1;
inline int multi_module_register_reply::module_info_size() const {
  return module_info_.size();
}
inline void multi_module_register_reply::clear_module_info() {
  module_info_.Clear();
}
inline ::CMSGProto::module_register_reply* multi_module_register_reply::mutable_module_info(int index) {
  // @@protoc_insertion_point(field_mutable:CMSGProto.multi_module_register_reply.module_info)
  return module_info_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_reply >*
multi_module_register_reply::mutable_module_info() {
  // @@protoc_insertion_point(field_mutable_list:CMSGProto.multi_module_register_reply.module_info)
  return &module_info_;
}
inline const ::CMSGProto::module_register_reply& multi_module_register_reply::module_info(int index) const {
  // @@protoc_insertion_point(field_get:CMSGProto.multi_module_register_reply.module_info)
  return module_info_.Get(index);
}
inline ::CMSGProto::module_register_reply* multi_module_register_reply::add_module_info() {
  // @@protoc_insertion_point(field_add:CMSGProto.multi_module_register_reply.module_info)
  return module_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CMSGProto::module_register_reply >&
multi_module_register_reply::module_info() const {
  // @@protoc_insertion_point(field_list:CMSGProto.multi_module_register_reply.module_info)
  return module_info_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CMSGProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ModuleRegister_2eproto
