// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModuleInfo.proto

#include "ModuleInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace CMSGProto {
class module_info_reqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<module_info_req>
      _instance;
} _module_info_req_default_instance_;
class module_info_replyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<module_info_reply>
      _instance;
} _module_info_reply_default_instance_;
}  // namespace CMSGProto
namespace protobuf_ModuleInfo_2eproto {
static void InitDefaultsmodule_info_req() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMSGProto::_module_info_req_default_instance_;
    new (ptr) ::CMSGProto::module_info_req();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CMSGProto::module_info_req::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_module_info_req =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmodule_info_req}, {}};

static void InitDefaultsmodule_info_reply() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::CMSGProto::_module_info_reply_default_instance_;
    new (ptr) ::CMSGProto::module_info_reply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CMSGProto::module_info_reply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_module_info_reply =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsmodule_info_reply}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_module_info_req.base);
  ::google::protobuf::internal::InitSCC(&scc_info_module_info_reply.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, pc_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, app_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, file_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, func_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, line_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, machine_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_req, time_),
  0,
  5,
  1,
  2,
  6,
  3,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_reply, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_reply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CMSGProto::module_info_reply, reply_),
  0,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, sizeof(::CMSGProto::module_info_req)},
  { 19, 25, sizeof(::CMSGProto::module_info_reply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::CMSGProto::_module_info_req_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::CMSGProto::_module_info_reply_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ModuleInfo.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020ModuleInfo.proto\022\tCMSGProto\"\210\001\n\017module"
      "_info_req\022\r\n\005pc_id\030\001 \002(\t\022\016\n\006app_id\030\002 \002(\005"
      "\022\021\n\tfile_name\030\003 \002(\t\022\021\n\tfunc_name\030\004 \002(\t\022\014"
      "\n\004line\030\005 \002(\005\022\024\n\014machine_name\030\006 \002(\t\022\014\n\004ti"
      "me\030\007 \002(\t\"\"\n\021module_info_reply\022\r\n\005reply\030\001"
      " \002(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 204);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ModuleInfo.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ModuleInfo_2eproto
namespace CMSGProto {

// ===================================================================

void module_info_req::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int module_info_req::kPcIdFieldNumber;
const int module_info_req::kAppIdFieldNumber;
const int module_info_req::kFileNameFieldNumber;
const int module_info_req::kFuncNameFieldNumber;
const int module_info_req::kLineFieldNumber;
const int module_info_req::kMachineNameFieldNumber;
const int module_info_req::kTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

module_info_req::module_info_req()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ModuleInfo_2eproto::scc_info_module_info_req.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMSGProto.module_info_req)
}
module_info_req::module_info_req(const module_info_req& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pc_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_pc_id()) {
    pc_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pc_id_);
  }
  file_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_file_name()) {
    file_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_name_);
  }
  func_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_func_name()) {
    func_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.func_name_);
  }
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_machine_name()) {
    machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
  }
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_time()) {
    time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
  }
  ::memcpy(&app_id_, &from.app_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&line_) -
    reinterpret_cast<char*>(&app_id_)) + sizeof(line_));
  // @@protoc_insertion_point(copy_constructor:CMSGProto.module_info_req)
}

void module_info_req::SharedCtor() {
  pc_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  file_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  func_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  machine_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&line_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(line_));
}

module_info_req::~module_info_req() {
  // @@protoc_insertion_point(destructor:CMSGProto.module_info_req)
  SharedDtor();
}

void module_info_req::SharedDtor() {
  pc_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  file_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  func_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  machine_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void module_info_req::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* module_info_req::descriptor() {
  ::protobuf_ModuleInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ModuleInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const module_info_req& module_info_req::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ModuleInfo_2eproto::scc_info_module_info_req.base);
  return *internal_default_instance();
}


void module_info_req::Clear() {
// @@protoc_insertion_point(message_clear_start:CMSGProto.module_info_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      pc_id_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      file_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      func_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      machine_name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      time_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 96u) {
    ::memset(&app_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&line_) -
        reinterpret_cast<char*>(&app_id_)) + sizeof(line_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool module_info_req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CMSGProto.module_info_req)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string pc_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pc_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->pc_id().data(), static_cast<int>(this->pc_id().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CMSGProto.module_info_req.pc_id");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 app_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_app_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &app_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string file_name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_file_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->file_name().data(), static_cast<int>(this->file_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CMSGProto.module_info_req.file_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string func_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_func_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->func_name().data(), static_cast<int>(this->func_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CMSGProto.module_info_req.func_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 line = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_line();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &line_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string machine_name = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machine_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machine_name().data(), static_cast<int>(this->machine_name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CMSGProto.module_info_req.machine_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string time = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->time().data(), static_cast<int>(this->time().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "CMSGProto.module_info_req.time");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMSGProto.module_info_req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMSGProto.module_info_req)
  return false;
#undef DO_
}

void module_info_req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMSGProto.module_info_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string pc_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pc_id().data(), static_cast<int>(this->pc_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.pc_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->pc_id(), output);
  }

  // required int32 app_id = 2;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->app_id(), output);
  }

  // required string file_name = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_name().data(), static_cast<int>(this->file_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.file_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->file_name(), output);
  }

  // required string func_name = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->func_name().data(), static_cast<int>(this->func_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.func_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->func_name(), output);
  }

  // required int32 line = 5;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->line(), output);
  }

  // required string machine_name = 6;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.machine_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->machine_name(), output);
  }

  // required string time = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time().data(), static_cast<int>(this->time().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->time(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CMSGProto.module_info_req)
}

::google::protobuf::uint8* module_info_req::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CMSGProto.module_info_req)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string pc_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pc_id().data(), static_cast<int>(this->pc_id().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.pc_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->pc_id(), target);
  }

  // required int32 app_id = 2;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->app_id(), target);
  }

  // required string file_name = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->file_name().data(), static_cast<int>(this->file_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.file_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->file_name(), target);
  }

  // required string func_name = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->func_name().data(), static_cast<int>(this->func_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.func_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->func_name(), target);
  }

  // required int32 line = 5;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->line(), target);
  }

  // required string machine_name = 6;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machine_name().data(), static_cast<int>(this->machine_name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.machine_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->machine_name(), target);
  }

  // required string time = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time().data(), static_cast<int>(this->time().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "CMSGProto.module_info_req.time");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->time(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMSGProto.module_info_req)
  return target;
}

size_t module_info_req::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:CMSGProto.module_info_req)
  size_t total_size = 0;

  if (has_pc_id()) {
    // required string pc_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pc_id());
  }

  if (has_file_name()) {
    // required string file_name = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file_name());
  }

  if (has_func_name()) {
    // required string func_name = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->func_name());
  }

  if (has_machine_name()) {
    // required string machine_name = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());
  }

  if (has_time()) {
    // required string time = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->time());
  }

  if (has_app_id()) {
    // required int32 app_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->app_id());
  }

  if (has_line()) {
    // required int32 line = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->line());
  }

  return total_size;
}
size_t module_info_req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMSGProto.module_info_req)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000007f) ^ 0x0000007f) == 0) {  // All required fields are present.
    // required string pc_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pc_id());

    // required string file_name = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->file_name());

    // required string func_name = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->func_name());

    // required string machine_name = 6;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->machine_name());

    // required string time = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->time());

    // required int32 app_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->app_id());

    // required int32 line = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->line());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void module_info_req::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMSGProto.module_info_req)
  GOOGLE_DCHECK_NE(&from, this);
  const module_info_req* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const module_info_req>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMSGProto.module_info_req)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMSGProto.module_info_req)
    MergeFrom(*source);
  }
}

void module_info_req::MergeFrom(const module_info_req& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMSGProto.module_info_req)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_pc_id();
      pc_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pc_id_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_file_name();
      file_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.file_name_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_func_name();
      func_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.func_name_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_machine_name();
      machine_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.machine_name_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_time();
      time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
    }
    if (cached_has_bits & 0x00000020u) {
      app_id_ = from.app_id_;
    }
    if (cached_has_bits & 0x00000040u) {
      line_ = from.line_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void module_info_req::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMSGProto.module_info_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void module_info_req::CopyFrom(const module_info_req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMSGProto.module_info_req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool module_info_req::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;
  return true;
}

void module_info_req::Swap(module_info_req* other) {
  if (other == this) return;
  InternalSwap(other);
}
void module_info_req::InternalSwap(module_info_req* other) {
  using std::swap;
  pc_id_.Swap(&other->pc_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  file_name_.Swap(&other->file_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  func_name_.Swap(&other->func_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  machine_name_.Swap(&other->machine_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  time_.Swap(&other->time_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(app_id_, other->app_id_);
  swap(line_, other->line_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata module_info_req::GetMetadata() const {
  protobuf_ModuleInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ModuleInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void module_info_reply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int module_info_reply::kReplyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

module_info_reply::module_info_reply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ModuleInfo_2eproto::scc_info_module_info_reply.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:CMSGProto.module_info_reply)
}
module_info_reply::module_info_reply(const module_info_reply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reply_ = from.reply_;
  // @@protoc_insertion_point(copy_constructor:CMSGProto.module_info_reply)
}

void module_info_reply::SharedCtor() {
  reply_ = 0;
}

module_info_reply::~module_info_reply() {
  // @@protoc_insertion_point(destructor:CMSGProto.module_info_reply)
  SharedDtor();
}

void module_info_reply::SharedDtor() {
}

void module_info_reply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* module_info_reply::descriptor() {
  ::protobuf_ModuleInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ModuleInfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const module_info_reply& module_info_reply::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ModuleInfo_2eproto::scc_info_module_info_reply.base);
  return *internal_default_instance();
}


void module_info_reply::Clear() {
// @@protoc_insertion_point(message_clear_start:CMSGProto.module_info_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reply_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool module_info_reply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CMSGProto.module_info_reply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 reply = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_reply();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &reply_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CMSGProto.module_info_reply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CMSGProto.module_info_reply)
  return false;
#undef DO_
}

void module_info_reply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CMSGProto.module_info_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 reply = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->reply(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CMSGProto.module_info_reply)
}

::google::protobuf::uint8* module_info_reply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CMSGProto.module_info_reply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 reply = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->reply(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMSGProto.module_info_reply)
  return target;
}

size_t module_info_reply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMSGProto.module_info_reply)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required int32 reply = 1;
  if (has_reply()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->reply());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void module_info_reply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CMSGProto.module_info_reply)
  GOOGLE_DCHECK_NE(&from, this);
  const module_info_reply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const module_info_reply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CMSGProto.module_info_reply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CMSGProto.module_info_reply)
    MergeFrom(*source);
  }
}

void module_info_reply::MergeFrom(const module_info_reply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CMSGProto.module_info_reply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_reply()) {
    set_reply(from.reply());
  }
}

void module_info_reply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CMSGProto.module_info_reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void module_info_reply::CopyFrom(const module_info_reply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMSGProto.module_info_reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool module_info_reply::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void module_info_reply::Swap(module_info_reply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void module_info_reply::InternalSwap(module_info_reply* other) {
  using std::swap;
  swap(reply_, other->reply_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata module_info_reply::GetMetadata() const {
  protobuf_ModuleInfo_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ModuleInfo_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace CMSGProto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CMSGProto::module_info_req* Arena::CreateMaybeMessage< ::CMSGProto::module_info_req >(Arena* arena) {
  return Arena::CreateInternal< ::CMSGProto::module_info_req >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::CMSGProto::module_info_reply* Arena::CreateMaybeMessage< ::CMSGProto::module_info_reply >(Arena* arena) {
  return Arena::CreateInternal< ::CMSGProto::module_info_reply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
